
FROM dmattli/debian-cuda:10.0-buster-runtime AS runtime
MAINTAINER dmm <dmm@mattli.us>

RUN apt-get update && apt-get install -y --no-install-recommends \
  libcudnn7-dev=7.6.3.30-1+cuda10.1 \
  cuda-toolkit-10-0 \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

